apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: bpg-watcher-dep
  namespace: ballerina-playground 
  labels: 
    app: bpg-watcher
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: bpg-watcher
  template: 
    metadata: 
      labels: 
        app: bpg-watcher
    spec: 
      serviceAccount: bpg-watcher-sa
      serviceAccountName: bpg-watcher-sa
      containers: 
      - name: bpg-watcher-container
        imagePullPolicy: Always 
        image: gcr.io/${BPG_GCP_PROJECT_ID}/controller:v0.1 
        # resources: 
        #   requests: 
        #     cpu: 100m 
        #     memory: 100Mi 
        env:
        -
          name: BPG_NAMESPACE
          value: "ballerina-playground"
        -
          name: BPG_CONTROLLER_ROLE
          value: "EVENT_WATCHER"
        -
          name: BPG_LAUNCHER_IMAGE_NAME
          value: "gcr.io/${BPG_GCP_PROJECT_ID}/launcher:v0.1-latest"
        -
          name: BGP_NFS_SERVER_IP
          value: "10.142.0.5"
        -
          name: BPG_REDIS_WRITE_HOST
          value: "redis-master"
        -
          name: BPG_REDIS_WRITE_PORT
          value: "6379"
        -
          name: BPG_REDIS_READ_HOST
          value: "redis-slave"
        -
          name: BPG_REDIS_READ_PORT
          value: "6379"
        -
          name: BPG_CONTROLLER_INTERNAL_URL
          value: "bpg-controller-internal"
        ports:
        -
          name: http-port
          containerPort: 8080
#        -
#          name: https-port
#          containerPort: 443
#        readinessProbe:
#          tcpSocket:
#            port: http-port
#          initialDelaySeconds: 3
#          periodSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: http-port
#          initialDelaySeconds: 5
#          periodSeconds: 20