site_name: Ballerina.io
repo_url: https://github.com/ballerina-platform/ballerina-www/blob/master/
edit_uri: website/main-pages/docs/
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
pages:
- Home : 'index.md'
- Philosophy : 'philosophy.md'
- Downloads : 'downloads.md'

theme: null
theme_dir: ballerina.io-website-theme
extra :
    latest_version : 0.970.0 alpha1
    latest_release_date : Apr 03, 2018     
