site_name: Ballerina.io
repo_url: https://github.com/ballerina-platform/ballerina-www/blob
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2017 WSO2, Inc.
pages:
- Learn : 'learn.md'
- Open Source : 'open-source.md'
- Help : 'help.md'
- License of site : 'license-of-site.md'
- Terms of Service : 'terms-of-service.md'
- Security : 'security.md'
- Relese Notes : 'downloads/release-notes.md'
- Quick Tour : 'learn/quick-tour.md'

theme: null
theme_dir: ballerina.io-two-col-theme
