site_name: Ballerina.io
repo_url: https://github.com/ballerinalang/ballerina
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2017 WSO2, Inc.
pages:
- Learn : 'learn.md'
- Open Source : 'open-source.md'
- Help : 'help.md'

theme: null
theme_dir: ballerina.io-two-col-theme
