site_name: Ballerina.io
repo_url: https://github.com/ballerina-platform/ballerina-www/blob/master/
edit_uri: website/two-column-pages/docs/
site_description: Documentation for the Ballerina Programming Language
site_author: WSO2, Inc.
copyright: 2018 WSO2, Inc.
pages:
- Learn: 'learn.md'
- Learn:
    - Quick Tour: 'learn/quick-tour.md'
    - Getting Started: 'learn/getting-started.md'
    - CLI commands: 'learn/cli-commands.md'
    - How to observe ballerina code: 'learn/how-to-observe-ballerina-code.md'
    - How to structure ballerina code: 'learn/how-to-structure-ballerina-code.md'
- Open Source : 'open-source.md'
- Open Source :
    - Slack : 'open-source/slack.md'
- Help : 'help.md'
- License of site : 'license-of-site.md'
- Terms of Service : 'terms-of-service.md'
- Security : 'security.md'
- Release Notes : 'downloads/release-notes.md'

theme: null
theme_dir: ballerina.io-two-col-theme
plugins: []
extra :
    base_download_url : 'https://product-dist.ballerina.io/downloads'
    archived_versions_json : 'https://product-dist.ballerina.io/downloads/archived_releases.json'
    archived_release_note_html : 'RELEASE_NOTE.html'
    nightly_versions_json : 'https://product-dist.ballerina.io/downloads/nightly_release.json'
    latest_versions_json : 'https://product-dist.ballerina.io/downloads/latest_release.json'
