apiVersion: v1 
kind: Service 
metadata: 
  annotations: 
    serviceloadbalancer/lb.cookie-sticky-session: "true" 
    serviceloadbalancer/lb.host: controller.playground.ballerina.io 
    # serviceloadbalancer/lb.sslTerm: "true" 
    # serviceloadbalancer/lb.routePath: "/api/run" 
  labels: 
    app: bpg-controller 
  name: bpg-controller 
  namespace: ballerina-playground 
spec: 
  ports: 
    - name: "web-port-http" 
      port: 80 
      targetPort: 8080 
    # - name: "web-port-https" 
    #   port: 443 
    #   targetPort: 443   
  selector: 
    app: bpg-controller 
 