apiVersion: apps/v1beta1
kind: Deployment 
metadata: 
  name: bpg-controller-dep 
  namespace: ballerina-playground 
  labels: 
    app: bpg-controller 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: bpg-controller 
  template: 
    metadata: 
      labels: 
        app: bpg-controller 
    spec: 
      serviceAccount: bpg-controller-sa 
      serviceAccountName: bpg-controller-sa 
      containers: 
      - name: bpg-controller-container 
        imagePullPolicy: Always 
        image: gcr.io/${BPG_GCP_PROJECT_ID}/controller:v0.1 
        # resources: 
        #   requests: 
        #     cpu: 100m 
        #     memory: 100Mi 
        env:
        -
          name: BPG_REDIS_WRITE_HOST
          value: "redis-master"
        -
          name: BPG_REDIS_WRITE_PORT
          value: "6379"
        -
          name: BPG_REDIS_READ_HOST
          value: "redis-slave"
        -
          name: BPG_REDIS_READ_PORT
          value: "6379"
        -
          name: DB_HOST
          value: "mysql-server"
        -
          name: DB_PORT
          value: "3306"
        -
          name: BPG_NAMESPACE
          value: "ballerina-playground"
        -
          name: BPG_LAUNCHER_IMAGE_NAME
          value: "gcr.io/${BPG_GCP_PROJECT_ID}/launcher:v0.1"
        -
          name: BPG_SCALING_MIN
          value: "3"
        -
          name: BPG_SCALING_MAX
          value: "8"
        -
          name: BPG_SCALING_STEP_UP
          value: "2"
        -
          name: BPG_SCALING_STEP_DOWN
          value: "1"
        -
          name: BPG_SCALING_LIMIT_GAP
          value: "2"
        -
          name: BPG_SCALING_IDLE_TIMEOUT_MIN
          value: "5"
        -
          name: BPG_CONTROLLER_ROLE
          value: "API_SERVER"
        ports:
        -
          name: http-port
          containerPort: 8080
#        -
#          name: https-port
#          containerPort: 443
        readinessProbe: 
          tcpSocket: 
            port: http-port 
          initialDelaySeconds: 3 
          periodSeconds: 10 
        livenessProbe: 
          tcpSocket: 
            port: http-port 
          initialDelaySeconds: 5 
          periodSeconds: 20 