apiVersion: apps/v1beta1 
kind: Deployment 
metadata: 
  name: bpg-controller-dep 
  namespace: ballerina-playground 
  labels: 
    app: bpg-controller 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: bpg-controller 
  template: 
    metadata: 
      labels: 
        app: bpg-controller 
    spec: 
      serviceAccount: bpg-controller-sa 
      serviceAccountName: bpg-controller-sa 
      containers: 
      - name: bpg-controller-container 
        imagePullPolicy: Always 
        image: gcr.io/${BPG_GCP_PROJECT_ID}/controller:v0.1 
        # resources: 
        #   requests: 
        #     cpu: 100m 
        #     memory: 100Mi 
        env:
        - name: BPG_REDIS_WRITE_HOST
          value: "redis-master"
        - name: BPG_REDIS_WRITE_PORT
          value: 6379
        - name: BPG_REDIS_READ_HOST
          value: "redis-slave"
        - name: BPG_REDIS_READ_PORT
          value: 6379
        - name: DB_HOST
          value: "mysql-server"
        - name: DB_PORT
          value: 3306
        ports: 
        - name: http-port 
          containerPort: 8080
        # - name: https-port 
          # containerPort: 443 
        readinessProbe: 
          tcpSocket: 
            port: http-port 
          initialDelaySeconds: 3 
          periodSeconds: 10 
        livenessProbe: 
          tcpSocket: 
            port: http-port 
          initialDelaySeconds: 5 
          periodSeconds: 20 