apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bpg-cache-responder-dep
  namespace: ballerina-playground
  labels:
    app: bpg-cache-responder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpg-cache-responder
  template:
    metadata:
      labels:
        app: bpg-cache-responder
    spec:
      containers:
      - name: bpg-cache-responder-container
        imagePullPolicy: Always
        image: gcr.io/${BPG_GCP_PROJECT_ID}/launcher:latest
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        env:
        - name: BPG_REDIS_WRITE_HOST
          value: "redis-master"
        - name: BPG_REDIS_READ_HOST
          value: "redis-slave"
        - name: BPG_CACHE_NODE
          value: "true"
        ports:
        - name: http-port
          containerPort: 80
        - name: https-port
          containerPort: 443
        readinessProbe:
          tcpSocket:
            port: https-port
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: https-port
          initialDelaySeconds: 5
          periodSeconds: 20
        # volumeMounts:
        # - mountPath: /mnt
        #   name: ballerina-nfs
      # volumes:
      # - name: ballerina-nfs
      #   nfs:
      #     path: /exports
      #     server: NFS_SERVER_IP
