apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: idlecheck
spec:
  schedule: "@hourly"
  # Do not allow concurrent runs
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure